# Generated by Django 5.1.4 on 2024-12-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Patient's phone number", max_length=9, unique=True
            ),
        ),
    ]
