# Generated by Django 5.1.3 on 2024-12-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='users.patient')),
            ],
            options={
                'ordering': ['doctor', 'date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='Specific date when the doctor is available')),
                ('start_time', models.TimeField(help_text='Start time for this schedule')),
                ('end_time', models.TimeField(help_text='End time for this schedule')),
                ('interval', models.TimeField(help_text='Time for one patient')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Time when the doctor's schedule was created")),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.doctor')),
            ],
            options={
                'ordering': ['doctor', 'work_date', 'start_time'],
            },
        ),
    ]
