# Generated by Django 5.1.5 on 2025-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for the appointment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_canceled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["doctor", "date", "time"],
            },
        ),
    ]
