# Generated by Django 5.1.7 on 2025-06-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        help_text="Specific date when the doctor is available"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time for this schedule"),
                ),
                ("end_time", models.TimeField(help_text="End time for this schedule")),
                (
                    "interval",
                    models.DurationField(help_text="Duration of one appointment slot"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the doctor's schedule was created",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["doctor", "work_date", "start_time"],
            },
        ),
    ]
