name: WszebiPatientPortal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12.8"]

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ vars.DB_USER }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      POETRY_VIRTUALENVS_CREATE:  false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Dependencies
      run: |
        poetry install --no-root
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        EMAIL_HOST: ${{ vars.EMAIL_HOST }}
        EMAIL_PORT: ${{ vars.EMAIL_PORT }}
        DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        DJANGO_ADMIN_PASSWORD: ${{ secrets.DJANGO_ADMIN_PASSWORD }}
    - name: Run Bandit
      run: |
        bandit -c bandit.yaml -r .
    - name: Run Ruff
      run: |
        ruff check
    - name: Run Safety
      run: |
        safety check
      continue-on-error: true
